name = "gleam_elli"
version = "0.5.0"
licences = ["Apache-2.0"]
description = "Run Gleam HTTP services with the Elli web server"

repository = { type = "github", user = "gleam-lang", repo = "elli" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.18"
gleam_http = "~> 3.0"
gleam_otp = "~> 0.3"
elli = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.1"
